development:
  adapter: postgresql
  encoding: utf8
  database: amandine
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: aphrodite_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: db
  pool: 5
  username: 
  password:

cucumber:
  <<: *TEST
